In [ ]:
import torch
# PyTorch提供了autograd包来自动根据输入和前向传播构建计算图，其中，backward函数可以很轻松的计算出梯度
# Tensor在pytorch中用来表示张量，且均为直接被我们创建的。如果我们想使用autograd包让它们参与梯度计算，则需要在创建它们的时候，将.requires_grad属性指定为true。
# 在梯度的反向计算过程中，只有叶子节点的梯度才会被填充。对于非叶子节点，如果要填充梯度信息，需要显式设置retain_grad=true。
a = torch.tensor([2.], requires_grad=True) # 定义a,b两个张量 requires_grad=True 的作用是让 backward 可以追踪这个参数并且计算它的梯度。
b = torch.tensor([1.], requires_grad=True)

c = a + b
d = b + 1
e = c * d

#为非叶节点填充的梯度
#在默认情况下，我们只能计算叶节点的导数值
# 中间节点的梯度值不会被保存，若想保存中间节点的梯度，我们可以使用retain_grad方法
c.retain_grad() # 通过.retain_grad()保留非任意节点的梯度值
d.retain_grad()
e.retain_grad()

print(c)
print(d)
print(e) #输出e的值

tensor([3.], grad_fn=<AddBackward0>)
tensor([2.], grad_fn=<AddBackward0>)
tensor([6.], grad_fn=<MulBackward0>)


In [ ]:
e.backward() #使用backward方法执行反向传播

In [ ]:
# 张量的grad属性存储了该点处的导数值。
print(a.grad) #a的梯度为2*1

In [ ]:
print(b.grad) #b的梯度为1*2+1*3

tensor([5.])


In [ ]:
print(a.grad, b.grad, c.grad, d.grad, e.grad) #c的梯度为2，d的梯度为5，e的梯度为1

tensor([2.]) tensor([5.]) tensor([2.]) tensor([3.]) tensor([1.])
